#ifndef SECTION_VAR_FAST_NO_INIT_BOOLEAN

#define SECTION_VAR_FAST_NO_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_FAST_NO_INIT_8

#define SECTION_VAR_FAST_NO_INIT_8

#endif

#ifndef SECTION_VAR_FAST_NO_INIT_16

#define SECTION_VAR_FAST_NO_INIT_16

#endif

#ifndef SECTION_VAR_FAST_NO_INIT_32

#define SECTION_VAR_FAST_NO_INIT_32

#endif

#ifndef SECTION_VAR_FAST_NO_INIT_UNSPECIFIED

#define SECTION_VAR_FAST_NO_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_FAST_INIT_BOOLEAN

#define SECTION_VAR_FAST_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_FAST_INIT_8

#define SECTION_VAR_FAST_INIT_8

#endif

#ifndef SECTION_VAR_FAST_INIT_16

#define SECTION_VAR_FAST_INIT_16

#endif

#ifndef SECTION_VAR_FAST_INIT_32

#define SECTION_VAR_FAST_INIT_32

#endif

#ifndef SECTION_VAR_FAST_INIT_UNSPECIFIED

#define SECTION_VAR_FAST_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_FAST_CLEARED_BOOLEAN

#define SECTION_VAR_FAST_CLEARED_BOOLEAN

#endif

#ifndef SECTION_VAR_FAST_CLEARED_8

#define SECTION_VAR_FAST_CLEARED_8

#endif

#ifndef SECTION_VAR_FAST_CLEARED_16

#define SECTION_VAR_FAST_CLEARED_16

#endif

#ifndef SECTION_VAR_FAST_CLEARED_32

#define SECTION_VAR_FAST_CLEARED_32

#endif

#ifndef SECTION_VAR_FAST_CLEARED_UNSPECIFIED

#define SECTION_VAR_FAST_CLEARED_UNSPECIFIED

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_INIT_BOOLEAN

#define SECTION_VAR_FAST_POWER_ON_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_INIT_8

#define SECTION_VAR_FAST_POWER_ON_INIT_8

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_INIT_16

#define SECTION_VAR_FAST_POWER_ON_INIT_16

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_INIT_32

#define SECTION_VAR_FAST_POWER_ON_INIT_32

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_INIT_UNSPECIFIED

#define SECTION_VAR_FAST_POWER_ON_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_BOOLEAN

#define SECTION_VAR_FAST_POWER_ON_CLEARED_BOOLEAN

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_8

#define SECTION_VAR_FAST_POWER_ON_CLEARED_8

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_16

#define SECTION_VAR_FAST_POWER_ON_CLEARED_16

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_32

#define SECTION_VAR_FAST_POWER_ON_CLEARED_32

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED

#define SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED

#endif

#ifndef SECTION_VAR_SLOW_NO_INIT_BOOLEAN

#define SECTION_VAR_SLOW_NO_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_SLOW_NO_INIT_8

#define SECTION_VAR_SLOW_NO_INIT_8

#endif

#ifndef SECTION_VAR_SLOW_NO_INIT_16

#define SECTION_VAR_SLOW_NO_INIT_16

#endif

#ifndef SECTION_VAR_SLOW_NO_INIT_32

#define SECTION_VAR_SLOW_NO_INIT_32

#endif

#ifndef SECTION_VAR_SLOW_NO_INIT_UNSPECIFIED

#define SECTION_VAR_SLOW_NO_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_SLOW_INIT_BOOLEAN

#define SECTION_VAR_SLOW_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_SLOW_INIT_8

#define SECTION_VAR_SLOW_INIT_8

#endif

#ifndef SECTION_VAR_SLOW_INIT_16

#define SECTION_VAR_SLOW_INIT_16

#endif

#ifndef SECTION_VAR_SLOW_INIT_32

#define SECTION_VAR_SLOW_INIT_32

#endif

#ifndef SECTION_VAR_SLOW_INIT_UNSPECIFIED

#define SECTION_VAR_SLOW_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_SLOW_CLEARED_BOOLEAN

#define SECTION_VAR_SLOW_CLEARED_BOOLEAN

#endif

#ifndef SECTION_VAR_SLOW_CLEARED_8

#define SECTION_VAR_SLOW_CLEARED_8

#endif

#ifndef SECTION_VAR_SLOW_CLEARED_16

#define SECTION_VAR_SLOW_CLEARED_16

#endif

#ifndef SECTION_VAR_SLOW_CLEARED_32

#define SECTION_VAR_SLOW_CLEARED_32

#endif

#ifndef SECTION_VAR_SLOW_CLEARED_UNSPECIFIED

#define SECTION_VAR_SLOW_CLEARED_UNSPECIFIED

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_INIT_BOOLEAN

#define SECTION_VAR_SLOW_POWER_ON_INIT_BOOLEAN

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_INIT_8

#define SECTION_VAR_SLOW_POWER_ON_INIT_8

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_INIT_16

#define SECTION_VAR_SLOW_POWER_ON_INIT_16

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_INIT_32

#define SECTION_VAR_SLOW_POWER_ON_INIT_32

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED

#define SECTION_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN

#define SECTION_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_CLEARED_8

#define SECTION_VAR_SLOW_POWER_ON_CLEARED_8

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_CLEARED_16

#define SECTION_VAR_SLOW_POWER_ON_CLEARED_16

#endif

#ifndef SECTION_VAR_SLOW_POWER_ON_CLEARED_32

#define SECTION_VAR_SLOW_POWER_ON_CLEARED_32

#endif

#ifndef SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED

#define SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED

#endif

#ifndef SECTION_CONST_BOOLEAN

#define SECTION_CONST_BOOLEAN

#endif

#ifndef SECTION_CONST_8

#define SECTION_CONST_8

#endif

#ifndef SECTION_CONST_16

#define SECTION_CONST_16

#endif

#ifndef SECTION_CONST_32

#define SECTION_CONST_32

#endif

#ifndef SECTION_CONST_UNSPECIFIED

#define SECTION_CONST_UNSPECIFIED

#endif

#ifndef SECTION_CODE_FAST

#define SECTION_CODE_FAST

#endif

#ifndef SECTION_CODE_SLOW

#define SECTION_CODE_SLOW

#endif

#if defined(MEMMAP_ERROR)

#error unterminated memory section.

#else

#define MEMMAP_ERROR

#endif

#if defined(CanTp_START_SEC_VAR_FAST_NO_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
SECTION_VAR_FAST_NO_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_NO_INIT_8)
#undef CanTp_START_SEC_VAR_FAST_NO_INIT_8
SECTION_VAR_FAST_NO_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_NO_INIT_16)
#undef CanTp_START_SEC_VAR_FAST_NO_INIT_16
SECTION_VAR_FAST_NO_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_NO_INIT_32)
#undef CanTp_START_SEC_VAR_FAST_NO_INIT_32
SECTION_VAR_FAST_NO_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
SECTION_VAR_FAST_NO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_FAST_INIT_BOOLEAN
SECTION_VAR_FAST_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_INIT_8)
#undef CanTp_START_SEC_VAR_FAST_INIT_8
SECTION_VAR_FAST_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_INIT_16)
#undef CanTp_START_SEC_VAR_FAST_INIT_16
SECTION_VAR_FAST_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_INIT_32)
#undef CanTp_START_SEC_VAR_FAST_INIT_32
SECTION_VAR_FAST_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_INIT_UNSPECIFIED
SECTION_VAR_FAST_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_CLEARED_BOOLEAN)
#undef CanTp_START_SEC_VAR_FAST_CLEARED_BOOLEAN
SECTION_VAR_FAST_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_CLEARED_8)
#undef CanTp_START_SEC_VAR_FAST_CLEARED_8
SECTION_VAR_FAST_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_CLEARED_16)
#undef CanTp_START_SEC_VAR_FAST_CLEARED_16
SECTION_VAR_FAST_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_CLEARED_32)
#undef CanTp_START_SEC_VAR_FAST_CLEARED_32
SECTION_VAR_FAST_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
SECTION_VAR_FAST_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
SECTION_VAR_FAST_POWER_ON_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_8)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_8
SECTION_VAR_FAST_POWER_ON_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_16)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_16
SECTION_VAR_FAST_POWER_ON_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_32)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_32
SECTION_VAR_FAST_POWER_ON_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
SECTION_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
SECTION_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_8)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
SECTION_VAR_FAST_POWER_ON_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_16)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
SECTION_VAR_FAST_POWER_ON_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_32)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
SECTION_VAR_FAST_POWER_ON_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
SECTION_VAR_SLOW_NO_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_NO_INIT_8)
#undef CanTp_START_SEC_VAR_SLOW_NO_INIT_8
SECTION_VAR_SLOW_NO_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_NO_INIT_16)
#undef CanTp_START_SEC_VAR_SLOW_NO_INIT_16
SECTION_VAR_SLOW_NO_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_NO_INIT_32)
#undef CanTp_START_SEC_VAR_SLOW_NO_INIT_32
SECTION_VAR_SLOW_NO_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
SECTION_VAR_SLOW_NO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_SLOW_INIT_BOOLEAN
SECTION_VAR_SLOW_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_INIT_8)
#undef CanTp_START_SEC_VAR_SLOW_INIT_8
SECTION_VAR_SLOW_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_INIT_16)
#undef CanTp_START_SEC_VAR_SLOW_INIT_16
SECTION_VAR_SLOW_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_INIT_32)
#undef CanTp_START_SEC_VAR_SLOW_INIT_32
SECTION_VAR_SLOW_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
SECTION_VAR_SLOW_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_CLEARED_BOOLEAN)
#undef CanTp_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
SECTION_VAR_SLOW_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_CLEARED_8)
#undef CanTp_START_SEC_VAR_SLOW_CLEARED_8
SECTION_VAR_SLOW_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_CLEARED_16)
#undef CanTp_START_SEC_VAR_SLOW_CLEARED_16
SECTION_VAR_SLOW_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_CLEARED_32)
#undef CanTp_START_SEC_VAR_SLOW_CLEARED_32
SECTION_VAR_SLOW_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
SECTION_VAR_SLOW_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
SECTION_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_8)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_8
SECTION_VAR_SLOW_POWER_ON_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_16)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_16
SECTION_VAR_SLOW_POWER_ON_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_32)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_32
SECTION_VAR_SLOW_POWER_ON_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
SECTION_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
SECTION_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
SECTION_VAR_SLOW_POWER_ON_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
SECTION_VAR_SLOW_POWER_ON_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
#undef CanTp_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
SECTION_VAR_SLOW_POWER_ON_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
#undef CanTp_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
SECTION_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CONST_BOOLEAN)
#undef CanTp_START_SEC_CONST_BOOLEAN
SECTION_CONST_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CONST_8)
#undef CanTp_START_SEC_CONST_8
SECTION_CONST_8
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CONST_16)
#undef CanTp_START_SEC_CONST_16
SECTION_CONST_16
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CONST_32)
#undef CanTp_START_SEC_CONST_32
SECTION_CONST_32
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CONST_UNSPECIFIED)
#undef CanTp_START_SEC_CONST_UNSPECIFIED
SECTION_CONST_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CODE_FAST)
#undef CanTp_START_SEC_CODE_FAST
SECTION_CODE_FAST
#undef MEMMAP_ERROR

#elif defined(CanTp_START_SEC_CODE_SLOW)
#undef CanTp_START_SEC_CODE_SLOW
SECTION_CODE_SLOW
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_NO_INIT_8)
#undef CanTp_STOP_SEC_VAR_FAST_NO_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_NO_INIT_16)
#undef CanTp_STOP_SEC_VAR_FAST_NO_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_NO_INIT_32)
#undef CanTp_STOP_SEC_VAR_FAST_NO_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_FAST_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_INIT_8)
#undef CanTp_STOP_SEC_VAR_FAST_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_INIT_16)
#undef CanTp_STOP_SEC_VAR_FAST_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_INIT_32)
#undef CanTp_STOP_SEC_VAR_FAST_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_CLEARED_8)
#undef CanTp_STOP_SEC_VAR_FAST_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_CLEARED_16)
#undef CanTp_STOP_SEC_VAR_FAST_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_CLEARED_32)
#undef CanTp_STOP_SEC_VAR_FAST_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_8)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_16)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_32)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_NO_INIT_8)
#undef CanTp_STOP_SEC_VAR_SLOW_NO_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_NO_INIT_16)
#undef CanTp_STOP_SEC_VAR_SLOW_NO_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_NO_INIT_32)
#undef CanTp_STOP_SEC_VAR_SLOW_NO_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_INIT_8)
#undef CanTp_STOP_SEC_VAR_SLOW_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_INIT_16)
#undef CanTp_STOP_SEC_VAR_SLOW_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_INIT_32)
#undef CanTp_STOP_SEC_VAR_SLOW_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_CLEARED_8)
#undef CanTp_STOP_SEC_VAR_SLOW_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_CLEARED_16)
#undef CanTp_STOP_SEC_VAR_SLOW_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_CLEARED_32)
#undef CanTp_STOP_SEC_VAR_SLOW_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
#undef CanTp_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
#undef CanTp_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CONST_BOOLEAN)
#undef CanTp_STOP_SEC_CONST_BOOLEAN
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CONST_8)
#undef CanTp_STOP_SEC_CONST_8
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CONST_16)
#undef CanTp_STOP_SEC_CONST_16
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CONST_32)
#undef CanTp_STOP_SEC_CONST_32
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CONST_UNSPECIFIED)
#undef CanTp_STOP_SEC_CONST_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CODE_FAST)
#undef CanTp_STOP_SEC_CODE_FAST
#undef MEMMAP_ERROR

#elif defined(CanTp_STOP_SEC_CODE_SLOW)
#undef CanTp_STOP_SEC_CODE_SLOW
#undef MEMMAP_ERROR

#else

#error undefined memory section used.

#endif /* #if defined(CanTp_START_SEC_VAR_FAST_NO_INIT_BOOLEAN) */
