name: test

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.PKG_REGISTRY_USERNAME}}
          password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
  run-tests:
    name: Run tests
    needs: build-and-push-image
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/sauci/cantp:develop
      credentials:
        username: ${{secrets.PKG_REGISTRY_USERNAME}}
        password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      volumes:
        - ${{github.workspace}}:/usr/project/cantp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run pytest tests
        run: mkdir build && cd build && cmake .. -DCANTP_ENABLE_TEST=ON && make all && ctest -V;gcov _cffi_can_tp.c
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./build/CanTp.c.gcov
