name: cantp CI

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  extract-metadata:
    name: Extract metadata
    runs-on: ubuntu-20.04
    steps:
     - name: Extract metadata (tags, labels) for Docker
       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
       with:
         images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    needs: extract-metadata
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.PKG_REGISTRY_USERNAME}}
          password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      - name: Echo metadata
        run: |
          echo "here we are...."
          echo ${{needs.extract-metadata.outputs.tags}}
          echo ${{needs.extract-metadata.outputs.labels}}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{needs.extract-metadata.outputs.tags}}
          labels: ${{needs.extract-metadata.outputs.labels}}
  run-tests:
    name: Run tests
    needs: build-and-push-image
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/sauci/cantp:develop
      credentials:
        username: ${{secrets.PKG_REGISTRY_USERNAME}}
        password: ${{secrets.PKG_REGISTRY_RW_TOKEN}}
      volumes:
        - ${{github.workspace}}:/usr/project/cantp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run pytest tests
        run: mkdir build && cd build && cmake .. -DCANTP_ENABLE_TEST=ON && make all && ctest -V && gcov _cffi_can_tp.c
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./build/CanTp.c.gcov
